import { Image } from "rsuite";

export default function SaWinner2025() {
  const awards = [
    {
      userCompany: "TKG SOLUTIONS PVT LTD",
      category: "Best AV Production - Corporate Events",
      parentCompany: "Tagglabs Experiential Private Limited",
      medal: "Gold",
      segment: "Corporate Events",
      participant: "Aishwarya Varma",
    },
    {
      userCompany: "TKG SOLUTIONS PVT LTD",
      category: "Best AV Production - Corporate Events",
      parentCompany: "Hertz and Pixelz",
      medal: "Silver",
      segment: "Corporate Events",
      participant: "Siddhartha Malik",
    },
    {
      userCompany: "TKG SOLUTIONS PVT LTD",
      category: "Best AV Production - Corporate Events",
      parentCompany: "Shivam Video Pvt. Ltd.",
      medal: "Bronze",
      segment: "Corporate Events",
      participant: "Yash Narula",
    },
    {
      userCompany: "TKG SOLUTIONS PVT LTD",
      category: "Best Catering Company - Corporate Events",
      parentCompany: "TKG Solutions Private Limited",
      medal: "Silver",
      segment: "Corporate Events",
      participant: "Manvir Singh Anand",
    },
    {
      userCompany: "TKG SOLUTIONS PVT LTD",
      category: "Best Corporate Gifting Company - Corporate Events",
      parentCompany: "Puneet Gupta Luxury",
      medal: "Gold",
      segment: "Corporate Events",
      participant: "Puneet Gupta",
    },
    {
      userCompany: "Dome Entertainment Pvt Ltd",
      category: "Best Event Venue - Corporate Events",
      parentCompany: "Dome Entertainment Pvt. Ltd.",
      medal: "Gold",
      segment: "Corporate Events",
      participant: "Pratik Burde",
    },
    {
      userCompany: "Dome Entertainment Pvt Ltd",
      category: "Best Hotel - Corporate Events (five star)",
      parentCompany: "Juniper Hotels Limited",
      medal: "Gold",
      segment: "Corporate Events",
      participant: "Khushi Kamboj",
    },
    {
      userCompany: "Dome Entertainment Pvt Ltd",
      category: "Best Hotel - Corporate Events (five star)",
      parentCompany: "Triton Hotels and resorts private Limited",
      medal: "Silver",
      segment: "Corporate Events",
      participant: "Randeep Kaur",
    },
    {
      userCompany: "Dome Entertainment Pvt Ltd",
      category: "Best Hotel - Corporate Events (five star)",
      parentCompany: "Soaltee Hotel Limited",
      medal: "Bronze",
      segment: "Corporate Events",
      participant: "Riya Neupane",
    },
    {
      userCompany: "35mmcandids",
      category: "Best Photography - Corporate Events",
      parentCompany: "35mmcandids",
      medal: "Bronze",
      segment: "Corporate Events",
      participant: "Aakash Tanawni",
    },
    {
      userCompany: "Renaissance",
      category: "Best Production House - Corporate Events",
      parentCompany: "RENAISSANCE",
      medal: "Gold",
      segment: "Corporate Events",
      participant: "Ragini Muralidharan",
    },
    {
      userCompany: "D K Production",
      category: "Best Production House - Corporate Events",
      parentCompany: "DK production",
      medal: "Silver",
      segment: "Corporate Events",
      participant: "Yash Jain",
    },
    {
      userCompany: "Event Network Entertainment Pvt. Ltd.",
      category: "Best Production House - Corporate Events",
      parentCompany: "Event network entertainment pvt ltd",
      medal: "Bronze",
      segment: "Corporate Events",
      participant: "Param Dhanoa",
    },
    {
      userCompany: "Dreamcast Digital Works Private Limited",
      category: "Best Registration Management Company - Corporate Events",
      parentCompany: "Dreamcast Digital Works Private Limited",
      medal: "Gold",
      segment: "Corporate Events",
      participant: "Gautam Seth",
    },
    {
      userCompany: "Dreamcast Digital Works Private Limited",
      category: "Best Registration Management Company - Corporate Events",
      parentCompany: "Magictap Solutions Private Limited",
      medal: "Silver",
      segment: "Corporate Events",
      participant: "Nikhil Tuteja",
    },
    {
      userCompany: "Renaissance",
      category: "Best Show Running Company-Corporate Events",
      parentCompany: "RENAISSANCE",
      medal: "Gold",
      segment: "Corporate Events",
      participant: "Ragini Muralidharan",
    },
    {
      userCompany: "Renaissance",
      category: "Best Show Running Company-Corporate Events",
      parentCompany: "BMEG Pvt Ltd - Verse",
      medal: "Silver",
      segment: "Corporate Events",
      participant: "Ritesh Chaudhary",
    },
    {
      userCompany: "Renaissance",
      category: "Best Show Running Company-Corporate Events",
      parentCompany: "Usually Unusual Entertainment",
      medal: "Bronze",
      segment: "Corporate Events",
      participant: "Keyur Shah",
    },
    {
      userCompany: "Renaissance",
      category: "Best Use of Technology - Corporate Events",
      parentCompany: "Tagglabs Experiential Private Limited",
      medal: "Gold",
      segment: "Corporate Events",
      participant: "Aishwarya Varma",
    },
    {
      userCompany: "Dreamcast Digital Works Private Limited",
      category: "Best Use of Technology - Corporate Events",
      parentCompany: "Dreamcast Digital Works Private Limited",
      medal: "Silver",
      segment: "Corporate Events",
      participant: "Gautam Seth",
    },
    {
      userCompany: "Dreamcast Digital Works Private Limited",
      category: "Best Use of Technology - Corporate Events",
      parentCompany: "DJ Interactive Solutions Pvt ltd",
      medal: "Bronze",
      segment: "Corporate Events",
      participant: "Abhishek Shrivastava",
    },
    {
      userCompany: "Dreamcast Digital Works Private Limited",
      category: "Best Videography - Corporate Events",
      parentCompany: "Lieux",
      medal: "Silver",
      segment: "Corporate Events",
      participant: "ARUN PRASAD P V",
    },
    {
      userCompany: "35mmcandids",
      category: "Best Videography - Corporate Events",
      parentCompany: "35mmcandids",
      medal: "Gold",
      segment: "Corporate Events",
      participant: "Aakash Tanawni",
    },
    {
      userCompany: "35mmcandids",
      category: "Best Videography - Corporate Events",
      parentCompany: "HAPPYSTILLZ PHOTOGRAPHY Pvt.Ltd",
      medal: "Bronze",
      segment: "Corporate Events",
      participant: "M Madhusudhan Rao",
    },
    {
      userCompany: "Bosco Dance Company",
      category: "Best Dance Choreographer - Entertainment",
      parentCompany: "Bosco Dance company",
      medal: "Gold",
      segment: "Entertainment",
      participant: "Bosco David",
    },
    {
      userCompany: "TeaAM5678 Dance Academy",
      category: "Best Dance Choreographer - Entertainment",
      parentCompany: "TeaAM5678 Dance Academy",
      medal: "Silver",
      segment: "Entertainment",
      participant: "S M VASANTH KUMAR",
    },
    {
      userCompany: "Zenith Dance Institute Pvt Ltd",
      category: "Best Dance Team - Entertainment",
      parentCompany: "Zenith Dance Institute Private Limited",
      medal: "Gold",
      segment: "Entertainment",
      participant: "Zenith Dance Company",
    },
    {
      userCompany: "DanceSmith Performing Arts Pvt.Ltd",
      category: "Best Dance Team - Entertainment",
      parentCompany: "DanceSmith Performing Arts Pvt.Ltd",
      medal: "Silver",
      segment: "Entertainment",
      participant: "Amit Verma",
    },
    {
      userCompany: "DanceSmith Performing Arts Pvt.Ltd",
      category: "Best DJ - Entertainment",
      parentCompany: "Sumit Sethi",
      medal: "Gold",
      segment: "Entertainment",
      participant: "Sumit Sethi",
    },
    {
      userCompany: "Prashant Gupta-DJ RIMI",
      category: "Best DJ - Entertainment",
      parentCompany: "DJ Rimi",
      medal: "Silver",
      segment: "Entertainment",
      participant: "Dj Rimi Gupta",
    },
    {
      userCompany: "Joypreet Singh Bindra",
      category: "Best DJ - Entertainment",
      parentCompany: "DJ Dippy Bindra",
      medal: "Bronze",
      segment: "Entertainment",
      participant: "Dippy Bindra",
    },
    {
      userCompany: "Freishia Mehelli Bomanbehram",
      category: "Best Emcee (FEMALE) - Entertainment",
      parentCompany: "Freishia Bomanbehram",
      medal: "Gold",
      segment: "Entertainment",
      participant: "Freishia Bomanbehram",
    },
    {
      userCompany: "Angela Rebello",
      category: "Best Emcee (FEMALE) - Entertainment",
      parentCompany: "Angela Rebello",
      medal: "Silver",
      segment: "Entertainment",
      participant: "angela rebello",
    },
    {
      userCompany: "Manoeuvre",
      category: "Best Emcee (FEMALE) - Entertainment",
      parentCompany: "Sanchali Arora",
      medal: "Bronze",
      segment: "Entertainment",
      participant: "Sanchali Arora",
    },
    {
      userCompany: "Aman Pawan Kumar Sharma",
      category: "Best Emcee (MALE) - Entertainment",
      parentCompany: "Aman Sharma",
      medal: "Gold",
      segment: "Entertainment",
      participant: "aman sharma",
    },
    {
      userCompany: "Mitin Upadhyay Prop: pankaj Kr Upadhyay",
      category: "Best Emcee (MALE) - Entertainment",
      parentCompany: "Mitin Upadhyay",
      medal: "Bronze",
      segment: "Entertainment",
      participant: "Mitin Upadhyay",
    },
    {
      userCompany: "Clince Varghese",
      category: "Best Emcee (MALE) - Entertainment",
      parentCompany: "Clince Varghese",
      medal: "Clince Varghese",
      segment: "Entertainment",
      participant: "Coach Clince",
    },
    {
      userCompany: "JEA Band",
      category: "Best Lawazma Band - Entertainment",
      parentCompany: "JEA Band",
      medal: "Gold",
      segment: "Entertainment",
      participant: "Karishma Thadani",
    },
    {
      userCompany: "JEA Band",
      category: "Best Lawazma Band - Entertainment",
      parentCompany: "SHANKAR LIGHTS AND GENERATOR",
      medal: "Silver",
      segment: "Entertainment",
      participant: "NIRMAL PHULWANI",
    },
    {
      userCompany: "Yours Eventfully",
      category: "Best Live Performer - Entertainment",
      parentCompany: "Yours Eventfully",
      medal: "Gold",
      segment: "Entertainment",
      participant: "Dhruv Rautela",
    },
    {
      userCompany: "Clince Varghese",
      category: "Best Live Performer - Entertainment",
      parentCompany: "Clince Varghese",
      medal: "Silver",
      segment: "Entertainment",
      participant: "Coach Clince",
    },
    {
      userCompany: "Lighthouse Entertainment (I) Pvt. Ltd",
      category: "Best Live Performer - Entertainment",
      parentCompany: "Martin D'souza",
      medal: "Bronze",
      segment: "Entertainment",
      participant: "Martin Dsouza",
    },
    {
      userCompany: "Lighthouse Entertainment (I) Pvt. Ltd",
      category: "Best Music Band - Entertainment",
      parentCompany: "STACCATO",
      medal: "Gold",
      segment: "Entertainment",
      participant: "Vikram Sarathy R",
    },
    {
      userCompany: "Yours Eventfully",
      category: "Best Music Band - Entertainment",
      parentCompany: "Yours Eventfully",
      medal: "Silver",
      segment: "Entertainment",
      participant: "Dhruv Rautela",
    },
    {
      userCompany: "Yours Eventfully",
      category: "Best Music Band - Entertainment",
      parentCompany: "SAMSHIVA BAND",
      medal: "Bronze",
      segment: "Entertainment",
      participant: "Bipasha Mitra",
    },
    {
      userCompany: "Yours Eventfully",
      category: "Best Team Building Company - Entertainment",
      parentCompany: "TBI Consulting Pvt.Ltd",
      medal: "Silver",
      segment: "Entertainment",
      participant: "Medha Sharma",
    },
    {
      userCompany: "Success Tea Consultants",
      category: "Best Team Building Company - Entertainment",
      parentCompany: "Success Tea Consultants",
      medal: "Gold",
      segment: "Entertainment",
      participant: "Alok Verma",
    },
    {
      userCompany: "Success Tea Consultants",
      category: "Best Team Building Company - Entertainment",
      parentCompany: "Graafeio",
      medal: "Bronze",
      segment: "Entertainment",
      participant: "Aliasger Saiger",
    },
    {
      userCompany: "Success Tea Consultants",
      category: "Best Team Building Emcee - Entertainment",
      parentCompany: "Clince Varghese",
      medal: "Gold",
      segment: "Entertainment",
      participant: "Coach Clince",
    },
    {
      userCompany: "FIREFLIES ENTERTAINMENT",
      category: "Best Team Building Emcee - Entertainment	",
      parentCompany: "Fireflies Entertainment",
      medal: "Silver",
      segment: "Entertainment",
      participant: "Maryann Manasseh",
    },
    {
      userCompany: "Rahil Khan",
      category: "Best Team Building Emcee - Entertainment",
      parentCompany: "Rahil Khan",
      medal: "Bronze",
      segment: "Entertainment",
      participant: "Rahil Khan",
    },
    {
      userCompany: "Rahil Khan",
      category: "Best AV Production Company- Festivals/Concerts",
      parentCompany: "PIXEL MEDIA",
      medal: "Gold",
      segment: "Festivals & Concerts",
      participant: "PXL MEDIA",
    },
    {
      userCompany: "SSL MEdia Technology and Solutions",
      category: "Best Lights Company- Festivals/Concerts",
      parentCompany: "SSL Media Technology & Solutions Pvt. Ltd.",
      medal: "Gold",
      segment: "Festivals & Concerts",
      participant: "ULHAS SAHASRABUDDHE",
    },
    {
      userCompany: "SSL MEdia Technology and Solutions",
      category: "Best Lights Company- Festivals/Concerts",
      parentCompany: "J DAVIS PROSOUND AND LIGHTING",
      medal: "Silver",
      segment: "Festivals & Concerts",
      participant: "Akshat V A",
    },
    {
      userCompany: "SSL MEdia Technology and Solutions",
      category: "Best Lights Company- Festivals/Concerts",
      parentCompany: "DHAWAN STAGECRAFTS PRIVATE LIMITED",
      medal: "Bronze",
      segment: "Festivals & Concerts",
      participant: "Sandeep Dhawan",
    },
    {
      userCompany: "Event Network Entertainment Pvt. Ltd.",
      category: "Best Production House-Festivals/Concerts",
      parentCompany: "Event network entertainment pvt ltd",
      medal: "Gold",
      segment: "Festivals & Concerts",
      participant: "Param Dhanoa",
    },
    {
      userCompany: "Renaissance",
      category: "Best Production House-Festivals/Concerts",
      parentCompany: "RENAISSANCE",
      medal: "Silver",
      segment: "Festivals & Concerts",
      participant: "Ragini Muralidharan",
    },
    {
      userCompany: "Renaissance",
      category: "Best Production House-Festivals/Concerts",
      parentCompany:
        "Vrnda Experiantial Marketing & Content Creators Private Limited",
      medal: "Bronze",
      segment: "Festivals & Concerts",
      participant: "Parth Desai",
    },
    {
      userCompany: "Dreamcast Digital Works Private Limited",
      category: "Best Registration Management Company-Festivals/Concerts",
      parentCompany: "Dreamcast Digital Works Private Limited",
      medal: "Gold",
      segment: "Festivals & Concerts",
      participant: "Gautam Seth",
    },
    {
      userCompany: "Renaissance",
      category: "Best Show Designing & Direction Company-Festivals/Concerts",
      parentCompany: "RENAISSANCE",
      medal: "Gold",
      segment: "Festivals & Concerts",
      participant: "Ragini Muralidharan",
    },
    {
      userCompany: "Dancing Peacock LLP",
      category: "Best Show Designing & Direction Company-Festivals/Concerts",
      parentCompany: "Dancing Peacock LLP",
      medal: "Silver",
      segment: "Festivals & Concerts",
      participant: "Ayush Maroo",
    },
    {
      userCompany: "Dancing Peacock LLP",
      category: "Best Show Designing & Direction Company-Festivals/Concerts",
      parentCompany: "Dancing Peacock LLP",
      medal: "Silver",
      segment: "Festivals & Concerts",
      participant: "Ayush Maroo",
    },
    {
      userCompany: "Dancing Peacock LLP",
      category: "Best Sound Company- Festivals/Concerts",
      parentCompany: "J DAVIS PROSOUND AND LIGHTING",
      medal: "Gold",
      segment: "Festivals & Concerts",
      participant: "Akshat V A",
    },
    {
      userCompany: "Renaissance",
      category: "Best Sound Company- Festivals/Concerts",
      parentCompany: "RENAISSANCE",
      medal: "Silver",
      segment: "Festivals & Concerts",
      participant: "Ragini Muralidharan",
    },
    {
      userCompany: "Dome Entertainment Pvt Ltd",
      category: "Best Venue-Festivals/Concerts",
      parentCompany: "Dome Entertainment Pvt. Ltd.",
      medal: "Gold",
      segment: "Festivals & Concerts",
      participant: "Pratik Burde",
    },
    {
      userCompany: "Dome Entertainment Pvt Ltd",
      category: "Best Hospitality Company - General Categories",
      parentCompany: "Heading Wedding Events Pvt. Ltd.",
      medal: "Gold",
      segment: "General Categories",
      participant: "Hari Mohan Jha",
    },
    {
      userCompany: "Dome Entertainment Pvt Ltd",
      category: "Best Hospitality Company - General Categories",
      parentCompany: "SKIL Travel Pvt Ltd",
      medal: "Silver",
      segment: "General Categories",
      participant: "Ramanpreet Singh",
    },
    {
      userCompany: "Dome Entertainment Pvt Ltd",
      category: "Best Hospitality Company - General Categories",
      parentCompany: "SQUADRON HOSPITALITY",
      medal: "Silver",
      segment: "General Categories",
      participant: "Md Aquib Hossain",
    },
    {
      userCompany: "Dome Entertainment Pvt Ltd",
      category: "Best Hospitality Company - General Categories",
      parentCompany: "Thank You Logistics Limited",
      medal: "Bronze",
      segment: "General Categories",
      participant: "Ashwini Arya",
    },
    {
      userCompany: "Dome Entertainment Pvt Ltd",
      category: "Best Light Company - General Categories",
      parentCompany: "THE PODIUM",
      medal: "Gold",
      segment: "General Categories",
      participant: "Umesh Kumar J",
    },
    {
      userCompany: "Dome Entertainment Pvt Ltd",
      category: "Best Lighting and trussing company - General Categories",
      parentCompany: "Devil Truss",
      medal: "Gold",
      segment: "General Categories",
      participant: "Giant truss",
    },
    {
      userCompany: "Dome Entertainment Pvt Ltd",
      category: "Best Logistics Company - General Categories",
      parentCompany: "FINEXX HOSPITALITY PVT LTD",
      medal: "Gold",
      segment: "General Categories",
      participant: "ALASSIM M",
    },
    {
      userCompany: "Dome Entertainment Pvt Ltd",
      category: "Best Logistics Company - General Categories",
      parentCompany: "SKIL Cabs Pvt Ltd",
      medal: "Silver",
      segment: "General Categories",
      participant: "Ramanpreet Singh",
    },
    {
      userCompany: "Dome Entertainment Pvt Ltd",
      category: "Best Logistics Company - General Categories",
      parentCompany: "CLASSIC ROVERS",
      medal: "Bronze",
      segment: "General Categories",
      participant: "Vikalp Kumar",
    },
    {
      userCompany: "Garnertech Innovation Private Limited",
      category: "Best Power distribution Company - General Categories",
      parentCompany: "Yellow Rentals(Garnertech Innovation Pvt Ltd.)",
      medal: "Gold",
      segment: "General Categories",
      participant: "Arpeet Gupta",
    },
    {
      userCompany: "Garnertech Innovation Private Limited",
      category: "Best Sound Company - General Categories",
      parentCompany: "PIXEL MEDIA",
      medal: "Gold",
      segment: "General Categories",
      participant: "PXL MEDIA",
    },
    {
      userCompany:
        "Entertainment Management & Promotional Consultants (Studio 69)",
      category: "Best Sound Company - General Categories",
      parentCompany:
        "Entertainment Management & Promotional Consultants (Studio 69)",
      medal: "Silver",
      segment: "General Categories",
      participant: "BHANU AHUJA",
    },
    {
      userCompany:
        "Entertainment Management & Promotional Consultants (Studio 69)",
      category: "Best Sound Company - General Categories",
      parentCompany: "THE PODIUM",
      medal: "Bronze",
      segment: "General Categories",
      participant: "Umesh Kumar J",
    },
    {
      userCompany: "TKG SOLUTIONS PVT LTD",
      category: "Best Catering Company - Government Events",
      parentCompany: "TKG Solutions Private Limited",
      medal: "Gold",
      segment: "Government Events",
      participant: "Manvir Singh Anand",
    },
    {
      userCompany: "TKG SOLUTIONS PVT LTD",
      category: "Best Use of Multimedia Technology-Government Events",
      parentCompany: "Tagglabs Experiential Private Limited",
      medal: "Gold",
      segment: "Government Events",
      participant: "Aishwarya Varma",
    },
    {
      userCompany: "TKG SOLUTIONS PVT LTD",
      category: "Best Use of Multimedia Technology-Government Events",
      parentCompany: "Otherlogic Creative Soltuions",
      medal: "Silver",
      segment: "Government Events",
      participant: "Nihar Mudgal",
    },
    {
      userCompany: "TKG SOLUTIONS PVT LTD",
      category: "Best Use of Multimedia Technology-Government Events",
      parentCompany: "Magictap Solutions Private Limited",
      medal: "Bronze",
      segment: "Government Events",
      participant: "Nikhil Tuteja",
    },
    {
      userCompany: "TKG SOLUTIONS PVT LTD",
      category: "Best Bar Management Company - Social Events/Wedding",
      parentCompany: "Drinq by Flaming Trio",
      medal: "Gold",
      segment: "Social Events/Weddings",
      participant: "Gagandeep Singh",
    },
    {
      userCompany: "TKG SOLUTIONS PVT LTD",
      category: "Best Bar Management Company - Social Events/Wedding",
      parentCompany: "House of Cocktails",
      medal: "Gold",
      segment: "Social Events/Weddings",
      participant: "Siddharth Aggarwal",
    },
    {
      userCompany: "AMM BRANDS LLP",
      category: "Best Bar Management Company - Social Events/Wedding",
      parentCompany: "Elixir Coterie",
      medal: "Silver",
      segment: "Social Events/Weddings",
      participant: "Archit Singhal",
    },
    {
      userCompany: "Shaken Hospitality",
      category: "Best Bar Management Company - Social Events/Wedding",
      parentCompany: "SHAKEN HOSPITALITY",
      medal: "Bronze",
      segment: "Social Events/Weddings",
      participant: "Raj Dabhi",
    },
    {
      userCompany: "Shaken Hospitality",
      category: "Best Catering Company - Social Events/Weddings",
      parentCompany: "RED CORAL THE COMPLETE CATERING SOLUTION",
      medal: "Gold",
      segment: "Social Events/Weddings",
      participant: "SAMMIR GOGIA",
    },
    {
      userCompany: "Kapco Banquets & Catering Pvt Ltd.",
      category: "Best Catering Company - Social Events/Weddings",
      parentCompany: "Kapco Banquets and Catering Pvt Ltd",
      medal: "Silver",
      segment: "Social Events/Weddings",
      participant: "Shreya Dutta",
    },
    {
      userCompany: "Kapco Banquets & Catering Pvt Ltd.",
      category: "Best Catering Company - Social Events/Weddings",
      parentCompany: "Millets Events & Dining",
      medal: "Bronze",
      segment: "Social Events/Weddings",
      participant: "Charul Sehra",
    },
    {
      userCompany: "Kapco Banquets & Catering Pvt Ltd.",
      category: "Best Decor & Design Company - Social Events/Weddings",
      parentCompany: "Konark Weddings",
      medal: "Gold",
      segment: "Social Events/Weddings",
      participant: "Konark Weddings",
    },
    {
      userCompany: "Kapco Banquets & Catering Pvt Ltd.",
      category: "Best Decor & Design Company - Social Events/Weddings",
      parentCompany: "GMS EVENT PLANNERS",
      medal: "Silver",
      segment: "Social Events/Weddings",
      participant: "Lalit Nayyar",
    },
    {
      userCompany: "Kapco Banquets & Catering Pvt Ltd.",
      category: "Best Decor & Design Company - Social Events/Weddings",
      parentCompany: "Festoon Props & Rentals LLP",
      medal: "Bronze",
      segment: "Social Events/Weddings",
      participant: "Minu Joy",
    },
    {
      userCompany: "Kapco Banquets & Catering Pvt Ltd.",
      category: "Best Digital Invitation Company - Social Events/Weddings",
      parentCompany: "Puneet Gupta Luxury",
      medal: "Gold",
      segment: "Social Events/Weddings",
      participant: "Puneet Gupta",
    },
    {
      userCompany: "Kapco Banquets & Catering Pvt Ltd.",
      category: "Best Digital Invitation Company - Social Events/Weddings",
      parentCompany: "WT Technlogies Pvt Ltd",
      medal: "Silver",
      segment: "Social Events/Weddings",
      participant: "Nilesh Tripathi",
    },
    {
      userCompany: "Kapco Banquets & Catering Pvt Ltd.",
      category: "Best Experiential Food Setup - Social Events/Weddings",
      parentCompany: "RED CORAL THE COMPLETE CATERING SOLUTION",
      medal: "Gold",
      segment: "Social Events/Weddings",
      participant: "SAMMIR GOGIA",
    },
    {
      userCompany: "Kapco Banquets & Catering Pvt Ltd.",
      category: "Best Experiential Food Setup - Social Events/Weddings",
      parentCompany: "Kapco Banquets and Catering Pvt Ltd",
      medal: "Silver",
      segment: "Social Events/Weddings",
      participant: "Shreya Dutta",
    },
    {
      userCompany: "Kapco Banquets & Catering Pvt Ltd.",
      category: "Best Experiential Food Setup - Social Events/Weddings",
      parentCompany: "Orange Blossom",
      medal: "Bronze",
      segment: "Social Events/Weddings",
      participant: "Amit Tyagi",
    },
    {
      userCompany: "Kapco Banquets & Catering Pvt Ltd.",
      category: "Best Floral Design & Decor - Social Events/Weddings",
      parentCompany: "A4 eventz Private Limited",
      medal: "Silver",
      segment: "Social Events/Weddings",
      participant: "Akhila Yenna",
    },
    {
      userCompany: "Kapco Banquets & Catering Pvt Ltd.",
      category: "Best Hair & Makeup Artist - Social Events/Weddings",
      parentCompany: "Sanchi Agarwal Makeovers",
      medal: "Silver",
      segment: "Social Events/Weddings",
      participant: "Sanchi Agarwal",
    },
    {
      userCompany: "Kapco Banquets & Catering Pvt Ltd.",
      category: "Best Hotel - Social Events/Wedding (five star)",
      parentCompany: "Juniper Hotels Limited",
      medal: "Gold",
      segment: "Social Events/Weddings",
      participant: "Khushi Kamboj",
    },
    {
      userCompany: "Kapco Banquets & Catering Pvt Ltd.",
      category: "Best Hotel - Social Events/Wedding (five star)",
      parentCompany: "Puducherry Backwater Resort Pvt Ltd",
      medal: "Silver",
      segment: "Social Events/Weddings",
      participant: "Anu Ilakkiya",
    },
    {
      userCompany: "Kapco Banquets & Catering Pvt Ltd.",
      category: "Best Hotel - Social Events/Wedding (five star)",
      parentCompany: "Triton Hotels and resorts private Limited",
      medal: "Bronze",
      segment: "Social Events/Weddings",
      participant: "Randeep Kaur",
    },
    {
      userCompany: "Kapco Banquets & Catering Pvt Ltd.",
      category: "Best Hotel - Social Events/Wedding (non five star)",
      parentCompany: "KANAKIA HOTELS & RESORTS PRIVATE LIMITED",
      medal: "Silver",
      segment: "Social Events/Weddings",
      participant: "Sonal Ram",
    },
    {
      userCompany: "35mmcandids",
      category: "Best Photography - Social Events/Weddings",
      parentCompany: "35mmcandids",
      medal: "Gold",
      segment: "Social Events/Weddings",
      participant: "Aakash Tanawni",
    },
    {
      userCompany: "35mmcandids",
      category: "Best Photography - Social Events/Weddings",
      parentCompany: "Delhi films/lbfilmz",
      medal: "Silver",
      segment: "Social Events/Weddings",
      participant: "Ankur saxxenaa",
    },
    {
      userCompany: "V.S Studio LLP",
      category: "Best Photography - Social Events/Weddings",
      parentCompany: "VS Studio",
      medal: "Bronze",
      segment: "Social Events/Weddings",
      participant: "Shristi Dhandharia",
    },
    {
      userCompany: "V.S Studio LLP",
      category: "Best Physical Invitation Company - Social Events/Weddings",
      parentCompany: "Puneet Gupta Luxury",
      medal: "Gold",
      segment: "Social Events/Weddings",
      participant: "Puneet Gupta",
    },
    {
      userCompany: "D K Production",
      category: "Best Production House - Social Events/Weddings",
      parentCompany: "DK production",
      medal: "Gold",
      segment: "Social Events/Weddings",
      participant: "Yash Jain",
    },
    {
      userCompany: "Renaissance",
      category: "Best Production House - Social Events/Weddings",
      parentCompany: "RENAISSANCE",
      medal: "Silver",
      segment: "Social Events/Weddings",
      participant: "AishwRagini Muralidharanarya",
    },
    {
      userCompany: "SOLUTIONS",
      category: "Best",
      parentCompany: "Tagglabs",
      medal: "Gold",
      segment: "Corporate",
      participant: "Aishwarya",
    },
    {
      userCompany: "SOLUTIONS",
      category: "Best",
      parentCompany: "Tagglabs",
      medal: "Gold",
      segment: "Corporate",
      participant: "Aishwarya",
    },
    {
      userCompany: "SOLUTIONS",
      category: "Best",
      parentCompany: "Tagglabs",
      medal: "Gold",
      segment: "Corporate",
      participant: "Aishwarya",
    },
    {
      userCompany: "SOLUTIONS",
      category: "Best",
      parentCompany: "Tagglabs",
      medal: "Gold",
      segment: "Corporate",
      participant: "Aishwarya",
    },
    {
      userCompany: "SOLUTIONS",
      category: "Best",
      parentCompany: "Tagglabs",
      medal: "Gold",
      segment: "Corporate",
      participant: "Aishwarya",
    },
    {
      userCompany: "SOLUTIONS",
      category: "Best",
      parentCompany: "Tagglabs",
      medal: "Gold",
      segment: "Corporate",
      participant: "Aishwarya",
    },
    {
      userCompany: "SOLUTIONS",
      category: "Best",
      parentCompany: "Tagglabs",
      medal: "Gold",
      segment: "Corporate",
      participant: "Aishwarya",
    },
    {
      userCompany: "SOLUTIONS",
      category: "Best",
      parentCompany: "Tagglabs",
      medal: "Gold",
      segment: "Corporate",
      participant: "Aishwarya",
    },
    {
      userCompany: "SOLUTIONS",
      category: "Best",
      parentCompany: "Tagglabs",
      medal: "Gold",
      segment: "Corporate",
      participant: "Aishwarya",
    },
    {
      userCompany: "SOLUTIONS",
      category: "Best",
      parentCompany: "Tagglabs",
      medal: "Gold",
      segment: "Corporate",
      participant: "Aishwarya",
    },
  ];

  //   const awards = [
  //     {
  //       userCompany: "SOLUTIONS",
  //       category: "Best",
  //       parentCompany: "Tagglabs",
  //       medal: "Gold",
  //       segment: "Corporate",
  //       participant: "Aishwarya",
  //     },
  //   ];

  return (
    <section className=" text-black ">
      <Image
        src="https://www.eemaindia.com/spotlightaward/assets/images/winner-2025.jpg"
        alt="spotlight awards 2025 winner banner"
      />

      <div className=" overflow-hidden px-4 py-11 ">
        <h2 className=" tracking-tight font-bold text-3xl md:text-4xl text-center mb-11 ">
          Spotlight Awards
        </h2>
        <div className="overflow-x-auto bg-orange-200 rounded-xl p-4">
          <table className="min-w-full text-left text-sm text-black border-collapse">
            <thead>
              <tr className="bg-orange-300 font-bold">
                <th className="px-4 py-2 border border-orange-400">
                  User Company
                </th>
                <th className="px-4 py-2 border border-orange-400">Category</th>
                <th className="px-4 py-2 border border-orange-400">
                  Parent Organisation/company/agency name
                </th>
                <th className="px-4 py-2 border border-orange-400">Metal</th>
                <th className="px-4 py-2 border border-orange-400">Segment</th>
                <th className="px-4 py-2 border border-orange-400">
                  Participant Name
                </th>
              </tr>
            </thead>
            <tbody>
              {awards.map((item, index) => (
                <tr key={index} className="even:bg-orange-100">
                  <td className="px-4 py-2 border border-orange-300">
                    {item.userCompany}
                  </td>
                  <td className="px-4 py-2 border border-orange-300">
                    {item.category}
                  </td>
                  <td className="px-4 py-2 border border-orange-300">
                    {item.parentCompany}
                  </td>
                  <td className="px-4 py-2 border border-orange-300">
                    {item.medal}
                  </td>
                  <td className="px-4 py-2 border border-orange-300">
                    {item.segment}
                  </td>
                  <td className="px-4 py-2 border border-orange-300">
                    {item.participant}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </section>
  );
}
